# Generated by Django 3.1.4 on 2020-12-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('quiz_id', models.IntegerField(editable=False, verbose_name='ID of Quiz')),
                ('rating', models.FloatField(verbose_name='Успешность чувака')),
                ('pass_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quiz_name', models.CharField(max_length=50, verbose_name='Название теста')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=100, verbose_name='Формулировка вопроса')),
                ('text', models.CharField(max_length=250, verbose_name='Текст вопроса')),
                ('image', models.CharField(max_length=100, verbose_name='Ссылка на картинку')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Несколько ответов')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questie.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questie.question')),
            ],
        ),
    ]
