# Generated by Django 3.1.4 on 2021-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$3t6xKcZgSP0V$/rtXZXf1ukmVRlf6pv7HUuqLBXzPAWQNkV5ITihJ2GE=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$eXS7M0LFa184$19tINTjYsBDj1xKhZowtoz7HUdnOo6EJ16gF8ZMQEb4=', max_length=16),
        ),
    ]
