# Generated by Django 3.1.4 on 2021-01-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0002_auto_20210113_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$TllsInMqcqC5$s8TfPgp/1gC9QBDOPlz1/fTbatPm0PH6juIA+7gzkNk=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$7xSTC9oTh5tK$nK7ho1oLkHP6JxcNQMP0/DlX9KjFfa8jFNMQzjwhM0w=', max_length=16),
        ),
    ]
