# Generated by Django 3.1.4 on 2021-01-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0003_auto_20210113_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$iE7MCeVbm2sd$tP/fA60ei5mQZEIrQe78FTtxso59UBm0lC1T6+cE05o=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$P4LkI5Agqdca$p1UvK/KXsUChhHvHch+Sjdo3x42EUx2AyNDour5fJAo=', max_length=16),
        ),
    ]
