# Generated by Django 3.1.4 on 2021-01-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0004_auto_20210114_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$EI0BCEHSuAi6$YBpnz+M6lxljZob7ROhigtzROjYMGKYAHeZ6To4tSyc=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$4E1QAM2lKvxP$Ue86P1P76zh7u6724XUUinL/FWZJw4uw0v0SuOKOk7E=', max_length=16),
        ),
    ]
