# Generated by Django 3.1.4 on 2020-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0004_quiz_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='quiz_id',
            field=models.UUIDField(editable=False, verbose_name='ID of Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичний тест?'),
        ),
    ]
