# Generated by Django 3.1.4 on 2020-12-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0005_auto_20201216_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='rating',
            field=models.FloatField(editable=False, verbose_name='Успешность чувака'),
        ),
    ]
