# Generated by Django 3.1.4 on 2021-01-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0005_auto_20210114_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$MDJicqChJPD9$RmaCRExcjmqCRjQHSAhn2nn/Pw0t65Stafe/x2eGfWY=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$r5A5JLNyp5xl$NXwSTXPSXshEkRGRB3NWZy5fZKnyPDFNewRHtnxywzo=', max_length=16),
        ),
    ]
