# Generated by Django 3.1.4 on 2021-01-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0006_auto_20210114_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$ksv2EQyAx23t$/S+sg3R9R9bs5Ta/Ur3ygeSkYxuogNQJp2KEv8w23SM=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$dovKMW0QvyFb$ZrmcRZbwdGyvk8IhSsgPw5l3Ax2p8mVIZ5qgfTIk2Jg=', max_length=16),
        ),
    ]
