# Generated by Django 3.1.4 on 2021-01-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0010_auto_20210114_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$tOp8QIHuEeIn$vattN85DZW+FKFZjp+mAaktdCfsdp3c9RMc7mBycNQA=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$1BHvBuQH6x4f$dUcb7FiIf5vlsnlUFYTdPdllp4YTvOI/PS2kXQPTBAc=', max_length=16),
        ),
    ]
