# Generated by Django 3.1.4 on 2021-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0011_auto_20210114_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$7YZBxyiXY5Zm$2Q2ZRszdYR2JlKfVwSXNhQFA93W0h4eFbNh9Om74aOA=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$tH0Xw98kgZSX$/REO/481ZZEhPDdxVUhMcuuSdXBDk4v3+TcvxSGksAQ=', max_length=16),
        ),
    ]
