# Generated by Django 3.1.4 on 2021-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0012_auto_20210114_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$HdpbrQXyuSye$Hrh6/UM/F0Db4Ou8cTpTYb0SKFRm2ry2xpSsgXsx4u4=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$1uGZm3Rasf0h$s+OnsjF2iS6SM2grSTHbf+yVE0MaVaEx53DqVWzZ0f0=', max_length=16),
        ),
    ]
