# Generated by Django 3.1.4 on 2021-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0015_auto_20210114_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$0ixiS11POajE$O0hhjrTd6TpkEpxShWzFN+Zs3xRfG+7YNNxopyNvVQw=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$7DCSet9PEIIh$jFmgdW4nQF2PQYEsmBxt+xbVGtMUUT6HHHz4QiotNHU=', max_length=16),
        ),
    ]
