# Generated by Django 3.1.4 on 2021-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0016_auto_20210114_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$AGUC6S8kvTZS$Y+uwAAuU19zwts4+OGwReJ61Jb2suVqeE9JzBi1YZNM=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$3vCN5tJIoXan$1RXDV5nAaIPswQ/tSZv+UD5XTbEuarYhJi2kFAvirSE=', max_length=16),
        ),
    ]

