# Generated by Django 3.1.4 on 2021-01-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0017_auto_20210114_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='quiz',
        ),
        migrations.AddField(
            model_name='result',
            name='quizie',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='questie.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$ofzFC7oZU3Jg$5UYHTD2N05kem0oX7bAHctShfqI45bHfPy3Bv8670fk=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$0KouDPofZ9QF$LAMGhf+CITCafBXmEbQ2ARvW+QzVIOslhGbBIRX7vug=', max_length=16),
        ),
    ]
