# Generated by Django 3.1.4 on 2021-01-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questie', '0018_auto_20210114_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='quizie',
            new_name='quiz',
        ),
        migrations.AlterField(
            model_name='dude',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$jyb5tHUeY4r8$D10hcFH/vD495w6uNLaV4F//qY4dxkj6sjVbkjZ6mjY=', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='editing_key',
            field=models.CharField(blank=True, default='pbkdf2_sha256$216000$rNQK8ig5APF1$qmSoU5dl0GtmPhz2xh64yc0OTxS/fyY8xgEU79TO/XY=', max_length=16),
        ),
    ]
